name: Generate RSS

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-jammy

    permissions:
      contents: write

    defaults:
      run:
        working-directory: /__w/oaktree-memo-rss/oaktree-memo-rss  # ✅ Git repo 正確位置

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build feed
        run: node scripts/scrape.mjs

      - name: Commit & push feed.xml
        run: |
          git config --global --add safe.directory $(pwd)
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/feed.xml
          git commit -m "chore: update feed.xml" || echo "No changes"
          git push
